---
abstract: 'Provide statistica-based pixel filters.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Imager-Filter-Statistic
requires:
  Imager: '0'
  Imager::Color: '0'
  List::Util: '0'
  List::UtilsBy: '0'
  strict: '0'
  warnings: '0'
version: '0.001'
